### ISSUE TITLE
Deploying Portfolio to GitHub Pages

### ISSUE THREAD

**Issue by TekyRey** [TekyRey/Portfolio#8]
### **Deploying Portfolio to GitHub Pages**

In this project I :

- Deployed my portfolio to github pages and here is the link
[https://tekyrey.github.io/Portfolio/](url)

**Comment by t-yanick** [comment]
Hi @TekyRey, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
